// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedFile(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "generated-files-test")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	tests := []struct {
		name        string
		path        string
		content     string
		isGenerated bool
	}{
		{
			name:        "zz_generated prefix",
			path:        "pkg/apis/v1/zz_generated.deepcopy.go",
			content:     "package v1\n",
			isGenerated: true,
		},
		{
			name:        "protobuf go",
			path:        "pkg/apis/v1/api.pb.go",
			content:     "package v1\n",
			isGenerated: true,
		},
		{
			name:        "normal go file",
			path:        "pkg/apis/v1/types.go",
			content:     "package v1\n// This is a normal file\n",
			isGenerated: false,
		},
		{
			name:        "generated header go",
			path:        "pkg/client/clientset.go",
			content:     "// Code generated by client-gen. DO NOT EDIT.\npackage client\n",
			isGenerated: true,
		},
		{
			name:        "generated header shell",
			path:        "scripts/install.sh",
			content:     "#!/bin/bash\n// Code generated by installer-gen. DO NOT EDIT.\n",
			isGenerated: true,
		},
		{
			name:        "generated header case insensitive",
			path:        "pkg/generated.txt",
			content:     "// code generated by something. do not edit.\n",
			isGenerated: true,
		},
		{
			name:        "not generated but has comments",
			path:        "pkg/utils.go",
			content:     "// This code generates numbers.\n// Please do not edit this comment.\n",
			isGenerated: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			fullPath := filepath.Join(tmpDir, tc.path)
			if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
				t.Fatalf("Failed to create parent dirs: %v", err)
			}
			if err := os.WriteFile(fullPath, []byte(tc.content), 0644); err != nil {
				t.Fatalf("Failed to write file: %v", err)
			}

			if got := IsGeneratedFile(tmpDir, tc.path); got != tc.isGenerated {
				t.Errorf("IsGeneratedFile(%q) = %v, want %v", tc.path, got, tc.isGenerated)
			}
		})
	}
}
