package commands

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"

	"k8s.io/klog/v2"
)

// IsGeneratedFile checks if a file is generated code.
// It checks the file path and the file content (header).
func IsGeneratedFile(repoDir, path string) bool {
	// 1. Check file path/name patterns
	baseName := filepath.Base(path)
	if strings.HasPrefix(baseName, "zz_generated") {
		return true
	}
	if strings.HasSuffix(baseName, ".pb.go") {
		return true
	}
	if strings.HasSuffix(baseName, "_pb2.py") {
		return true
	}

	// 2. Check file content for generated header
	fullPath := filepath.Join(repoDir, path)
	file, err := os.Open(fullPath)
	if err != nil {
		// If file doesn't exist (e.g. deleted file), we can't check content.
		// Assume not generated unless path matched.
		if os.IsNotExist(err) {
			return false
		}
		klog.V(4).Infof("Failed to open file to check if generated: %s, error: %v", fullPath, err)
		return false
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	// Check first 20 lines (standard practice)
	maxLines := 20
	lineCount := 0
	for scanner.Scan() {
		line := scanner.Text()
		lineCount++
		if lineCount > maxLines {
			break
		}

		// Common generated code markers
		lowerLine := strings.ToLower(line)
		if strings.Contains(lowerLine, "code generated by") && strings.Contains(lowerLine, "do not edit") {
			return true
		}
		if strings.Contains(lowerLine, "autogenerated by") && strings.Contains(lowerLine, "do not edit") {
			return true
		}
	}

	return false
}

// IsIgnoredFile checks if a file matches any of the ignore patterns.
func IsIgnoredFile(path string, ignorePatterns []string) bool {
	for _, pattern := range ignorePatterns {
		matched, err := filepath.Match(pattern, path)
		if err == nil && matched {
			return true
		}
		// Also match if the pattern is a directory and the file is inside it
		// e.g. pattern "vendor/" matches "vendor/foo.go"
		// filepath.Match doesn't handle directory recursion implicitly like gitignore.
		// So we might want to check prefix if pattern ends with separator.
		// However, standard glob usually implies ** for recursion.
		// Let's assume standard filepath.Match for now.
		// If users want to ignore a directory, they should probably use "dir/*" or "dir/**" if supported?
		// filepath.Match does NOT support **.
		// So "dir/*" only matches files in dir.
		// To be more user friendly, if pattern ends with /, we treat it as directory prefix.
		if strings.HasSuffix(pattern, "/") {
			if strings.HasPrefix(path, pattern) {
				return true
			}
		}
	}
	return false
}
