// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"

	"k8s.io/klog/v2"
)

// IsGeneratedFile checks if a file is generated code.
// It checks the file path and the file content (header).
func IsGeneratedFile(repoDir, path string) bool {
	// 1. Check file path/name patterns
	baseName := filepath.Base(path)
	if strings.HasPrefix(baseName, "zz_generated") {
		return true
	}
	if strings.HasSuffix(baseName, ".pb.go") {
		return true
	}
	if strings.HasSuffix(baseName, "_pb2.py") {
		return true
	}

	// 2. Check file content for generated header
	fullPath := filepath.Join(repoDir, path)
	file, err := os.Open(fullPath)
	if err != nil {
		// If file doesn't exist (e.g. deleted file), we can't check content.
		// Assume not generated unless path matched.
		if os.IsNotExist(err) {
			return false
		}
		klog.V(4).Infof("Failed to open file to check if generated: %s, error: %v", fullPath, err)
		return false
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	// Check first 20 lines (standard practice)
	maxLines := 20
	lineCount := 0
	for scanner.Scan() {
		line := scanner.Text()
		lineCount++
		if lineCount > maxLines {
			break
		}

		// Common generated code markers
		lowerLine := strings.ToLower(line)
		if strings.Contains(lowerLine, "code generated by") && strings.Contains(lowerLine, "do not edit") {
			return true
		}
		if strings.Contains(lowerLine, "autogenerated by") && strings.Contains(lowerLine, "do not edit") {
			return true
		}
	}

	return false
}
