package commands

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedFile(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "generated-files-test")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	tests := []struct {
		name        string
		path        string
		content     string
		isGenerated bool
	}{
		{
			name:        "zz_generated prefix",
			path:        "pkg/apis/v1/zz_generated.deepcopy.go",
			content:     "package v1\n",
			isGenerated: true,
		},
		{
			name:        "protobuf go",
			path:        "pkg/apis/v1/api.pb.go",
			content:     "package v1\n",
			isGenerated: true,
		},
		{
			name:        "normal go file",
			path:        "pkg/apis/v1/types.go",
			content:     "package v1\n// This is a normal file\n",
			isGenerated: false,
		},
		{
			name:        "generated header go",
			path:        "pkg/client/clientset.go",
			content:     "// Code generated by client-gen. DO NOT EDIT.\npackage client\n",
			isGenerated: true,
		},
		{
			name:        "generated header shell",
			path:        "scripts/install.sh",
			content:     "#!/bin/bash\n// Code generated by installer-gen. DO NOT EDIT.\n",
			isGenerated: true,
		},
		{
			name:        "generated header case insensitive",
			path:        "pkg/generated.txt",
			content:     "// code generated by something. do not edit.\n",
			isGenerated: true,
		},
		{
			name:        "not generated but has comments",
			path:        "pkg/utils.go",
			content:     "// This code generates numbers.\n// Please do not edit this comment.\n",
			isGenerated: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			fullPath := filepath.Join(tmpDir, tc.path)
			if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
				t.Fatalf("Failed to create parent dirs: %v", err)
			}
			if err := os.WriteFile(fullPath, []byte(tc.content), 0644); err != nil {
				t.Fatalf("Failed to write file: %v", err)
			}

			if got := IsGeneratedFile(tmpDir, tc.path); got != tc.isGenerated {
				t.Errorf("IsGeneratedFile(%q) = %v, want %v", tc.path, got, tc.isGenerated)
			}
		})
	}
}
