package commands

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/klog/v2"
)

type KubeClient struct {
	restConfig       *rest.Config
	httpClient       *http.Client
	CurrentNamespace string
}

func NewKubeClient() (*KubeClient, error) {
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	configOverrides := &clientcmd.ConfigOverrides{}
	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)

	restConfig, err := kubeConfig.ClientConfig()
	if err != nil {
		return nil, fmt.Errorf("failed to load kubeconfig: %w", err)
	}

	httpClient, err := rest.HTTPClientFor(restConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to create HTTP client: %w", err)
	}

	namespace, _, err := kubeConfig.Namespace()
	if err != nil {
		return nil, fmt.Errorf("failed to get namespace from kubeconfig: %w", err)
	}

	return &KubeClient{restConfig: restConfig, httpClient: httpClient, CurrentNamespace: namespace}, nil
}

// GetClientset returns a new Kubernetes clientset.
func (k *KubeClient) GetClientset() (*kubernetes.Clientset, error) {
	clientset, err := kubernetes.NewForConfigAndClient(k.restConfig, k.httpClient)
	if err != nil {
		return nil, fmt.Errorf("failed to create kubernetes client: %w", err)
	}
	return clientset, nil
}

// GetDynamicClient returns a new dynamic client.
func (k *KubeClient) GetDynamicClient() (dynamic.Interface, error) {
	client, err := dynamic.NewForConfigAndClient(k.restConfig, k.httpClient)
	if err != nil {
		return nil, fmt.Errorf("failed to create dynamic client: %w", err)
	}
	return client, nil
}

// findSandboxPod finds the pod for the given sandbox name.
// If the pod is not found, it returns (nil, nil)
func findSandboxPod(ctx context.Context, sandboxName string) (*types.NamespacedName, error) {
	kube, err := NewKubeClient()
	if err != nil {
		return nil, err
	}

	clientset, err := kube.GetClientset()
	if err != nil {
		return nil, err
	}
	namespace := kube.CurrentNamespace

	// The sandbox name in the RGD is devc-<name>
	// And the pods have label sandbox=devc-<name>
	labelSelector := fmt.Sprintf("sandbox=devc-%s", sandboxName)
	pods, err := clientset.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: labelSelector,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list pods with selector %q: %w", labelSelector, err)
	}

	if len(pods.Items) == 0 {
		return nil, nil
	}

	// Pick the first running pod, or just the first one if none are running yet (though exec will fail)
	pod := &pods.Items[0]

	for _, p := range pods.Items {
		if p.Status.Phase == "Running" {
			pod = &p
			break
		}
	}

	podID := &types.NamespacedName{
		Name:      pod.Name,
		Namespace: pod.Namespace,
	}
	return podID, nil
}

// updateSSHConfig updates the user's SSH config to include the sandbox host.
func updateSSHConfig(ctx context.Context, path, host string, podID types.NamespacedName) error {
	sshDir := filepath.Dir(path)
	confDir := filepath.Join(sshDir, "config.d", "dev-sandboxes")
	if err := os.MkdirAll(confDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// 1. Ensure Include in main config
	includeLine := "Include config.d/dev-sandboxes/*"
	if err := ensureSSHConfigLine(ctx, path, includeLine); err != nil {
		return fmt.Errorf("failed to update main ssh config: %w", err)
	}

	// 2. Write sandbox config
	sandboxConfigPath := filepath.Join(confDir, host)

	block := []string{
		"# Generated by gemini-sandbox",
		fmt.Sprintf("Host %s", host),
		fmt.Sprintf("  ProxyCommand kubectl exec -i %s -n %s -- /repo-agent/dev-sandbox sshd", podID.Name, podID.Namespace),
		"  StrictHostKeyChecking no",
		"  UserKnownHostsFile /dev/null",
	}

	content := strings.Join(block, "\n")

	if err := os.WriteFile(sandboxConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write sandbox config: %w", err)
	}

	return nil
}

func ensureSSHConfigLine(ctx context.Context, path, line string) error {
	log := klog.FromContext(ctx)

	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}

		// Create new file
		content = []byte{}

		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			return err
		}

		log.Info("Creating new SSH config file", "path", path)
	}

	configStr := string(content)
	if strings.Contains(configStr, line) {
		return nil
	}

	// Prepend
	newConfig := line + "\n" + configStr
	log.Info("Adding include line to SSH config", "line", line)

	return os.WriteFile(path, []byte(newConfig), 0644)
}
