package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/gke-labs/gemini-for-kubernetes-development/repo-agent/pkg/sandbox"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/klog/v2"
)

// UpdateSSHConfig updates the user's SSH config to include the sandbox host.
func UpdateSSHConfig(ctx context.Context, path, host string, podID types.NamespacedName) error {
	sshDir := filepath.Dir(path)
	confDir := filepath.Join(sshDir, "config.d", "dev-sandboxes")
	if err := os.MkdirAll(confDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// 1. Ensure Include in main config
	includeLine := "Include config.d/dev-sandboxes/*"
	if err := ensureSSHConfigLine(ctx, path, includeLine); err != nil {
		return fmt.Errorf("failed to update main ssh config: %w", err)
	}

	// 2. Write sandbox config
	sandboxConfigPath := filepath.Join(confDir, host)

	block := []string{
		"# Generated by gemini-sandbox",
		fmt.Sprintf("Host %s", host),
		fmt.Sprintf("  ProxyCommand kubectl exec -i %s -n %s -- %s sshd", podID.Name, podID.Namespace, sandbox.RepoSandboxBinary),
		"  StrictHostKeyChecking no",
		"  UserKnownHostsFile /dev/null",
	}

	content := strings.Join(block, "\n")

	if err := os.WriteFile(sandboxConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write sandbox config: %w", err)
	}

	return nil
}

func ensureSSHConfigLine(ctx context.Context, path, line string) error {
	log := klog.FromContext(ctx)

	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}

		// Create new file
		content = []byte{}

		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			return err
		}

		log.Info("Creating new SSH config file", "path", path)
	}

	configStr := string(content)
	if strings.Contains(configStr, line) {
		return nil
	}

	// Prepend
	newConfig := line + "\n" + configStr
	log.Info("Adding include line to SSH config", "line", line)

	return os.WriteFile(path, []byte(newConfig), 0644)
}
