// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// you may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"k8s.io/apimachinery/pkg/types"
	"k8s.io/klog/v2"

	"github.com/gke-labs/gemini-for-kubernetes-development/repo-agent/pkg/sandbox"
)

// updateSSHConfig updates the SSH configuration for a dev sandbox.
func updateSSHConfig(ctx context.Context, path, host string, podID types.NamespacedName) error {
	sshDir := filepath.Dir(path)
	confDir := filepath.Join(sshDir, "config.d", "dev-sandboxes")
	if err := os.MkdirAll(confDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// 1. Ensure Include in main config
	includeLine := "Include config.d/dev-sandboxes/*"
	if err := ensureSSHConfigLine(ctx, path, includeLine); err != nil {
		return fmt.Errorf("failed to update main ssh config: %w", err)
	}

	// 2. Write sandbox config
	sandboxConfigPath := filepath.Join(confDir, host)

	block := []string{
		"# Generated by gemini-sandbox",
		fmt.Sprintf("Host %s", host),
		fmt.Sprintf("  ProxyCommand kubectl exec -i %s -n %s -- %s sshd", podID.Name, podID.Namespace, sandbox.RepoSandboxBinary),
		"  StrictHostKeyChecking no",
		"  UserKnownHostsFile /dev/null",
	}

	content := strings.Join(block, "\n")

	if err := os.WriteFile(sandboxConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write sandbox config: %w", err)
	}

	return nil
}

func ensureSSHConfigLine(ctx context.Context, path, line string) error {
	log := klog.FromContext(ctx)

	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}

		// Create new file
		content = []byte{}

		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			return err
		}

		log.Info("Creating new SSH config file", "path", path)
	}

	configStr := string(content)
	if strings.Contains(configStr, line) {
		return nil
	}

	// Prepend
	newConfig := line + "\n" + configStr
	log.Info("Adding include line to SSH config", "line", line)

	return os.WriteFile(path, []byte(newConfig), 0644)
}
