//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevSandbox) DeepCopyInto(out *DevSandbox) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevSandbox.
func (in *DevSandbox) DeepCopy() *DevSandbox {
	if in == nil {
		return nil
	}
	out := new(DevSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevSpec) DeepCopyInto(out *DevSpec) {
	*out = *in
	in.LLM.DeepCopyInto(&out.LLM)
	if in.Branches != nil {
		in, out := &in.Branches, &out.Branches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeBranches != nil {
		in, out := &in.ExcludeBranches, &out.ExcludeBranches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ideas != nil {
		in, out := &in.Ideas, &out.Ideas
		*out = make([]IdeaSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevSpec.
func (in *DevSpec) DeepCopy() *DevSpec {
	if in == nil {
		return nil
	}
	out := new(DevSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extension) DeepCopyInto(out *Extension) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extension.
func (in *Extension) DeepCopy() *Extension {
	if in == nil {
		return nil
	}
	out := new(Extension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdeaSpec) DeepCopyInto(out *IdeaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdeaSpec.
func (in *IdeaSpec) DeepCopy() *IdeaSpec {
	if in == nil {
		return nil
	}
	out := new(IdeaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueHandlerSpec) DeepCopyInto(out *IssueHandlerSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeLabels != nil {
		in, out := &in.ExcludeLabels, &out.ExcludeLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueHandlerSpec.
func (in *IssueHandlerSpec) DeepCopy() *IssueHandlerSpec {
	if in == nil {
		return nil
	}
	out := new(IssueHandlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueSpec) DeepCopyInto(out *IssueSpec) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeIssues != nil {
		in, out := &in.ExcludeIssues, &out.ExcludeIssues
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	in.LLM.DeepCopyInto(&out.LLM)
	if in.DraftPR != nil {
		in, out := &in.DraftPR, &out.DraftPR
		*out = new(bool)
		**out = **in
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Handlers != nil {
		in, out := &in.Handlers, &out.Handlers
		*out = make([]IssueHandlerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueSpec.
func (in *IssueSpec) DeepCopy() *IssueSpec {
	if in == nil {
		return nil
	}
	out := new(IssueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfig) DeepCopyInto(out *LLMConfig) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]Extension, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfig.
func (in *LLMConfig) DeepCopy() *LLMConfig {
	if in == nil {
		return nil
	}
	out := new(LLMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRReviewSpec) DeepCopyInto(out *PRReviewSpec) {
	*out = *in
	in.LLM.DeepCopyInto(&out.LLM)
	if in.IgnoreFiles != nil {
		in, out := &in.IgnoreFiles, &out.IgnoreFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PullRequests != nil {
		in, out := &in.PullRequests, &out.PullRequests
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ExcludePullRequests != nil {
		in, out := &in.ExcludePullRequests, &out.ExcludePullRequests
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.ExcludeLabels != nil {
		in, out := &in.ExcludeLabels, &out.ExcludeLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Assignees != nil {
		in, out := &in.Assignees, &out.Assignees
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRReviewSpec.
func (in *PRReviewSpec) DeepCopy() *PRReviewSpec {
	if in == nil {
		return nil
	}
	out := new(PRReviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatch) DeepCopyInto(out *RepoWatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatch.
func (in *RepoWatch) DeepCopy() *RepoWatch {
	if in == nil {
		return nil
	}
	out := new(RepoWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoWatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchList) DeepCopyInto(out *RepoWatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepoWatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchList.
func (in *RepoWatchList) DeepCopy() *RepoWatchList {
	if in == nil {
		return nil
	}
	out := new(RepoWatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoWatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchSpec) DeepCopyInto(out *RepoWatchSpec) {
	*out = *in
	in.Review.DeepCopyInto(&out.Review)
	if in.Issue != nil {
		in, out := &in.Issue, &out.Issue
		*out = new(IssueSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Dev.DeepCopyInto(&out.Dev)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchSpec.
func (in *RepoWatchSpec) DeepCopy() *RepoWatchSpec {
	if in == nil {
		return nil
	}
	out := new(RepoWatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchStatus) DeepCopyInto(out *RepoWatchStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReviewSandboxes != nil {
		in, out := &in.ReviewSandboxes, &out.ReviewSandboxes
		*out = make([]WatchedPR, len(*in))
		copy(*out, *in)
	}
	if in.PendingPRs != nil {
		in, out := &in.PendingPRs, &out.PendingPRs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.IssueSandboxes != nil {
		in, out := &in.IssueSandboxes, &out.IssueSandboxes
		*out = make(map[string][]WatchedIssue, len(*in))
		for key, val := range *in {
			var outVal []WatchedIssue
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]WatchedIssue, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.PendingIssues != nil {
		in, out := &in.PendingIssues, &out.PendingIssues
		*out = make(map[string][]int, len(*in))
		for key, val := range *in {
			var outVal []int
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]int, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.DevSandboxes != nil {
		in, out := &in.DevSandboxes, &out.DevSandboxes
		*out = make([]DevSandbox, len(*in))
		copy(*out, *in)
	}
	if in.PendingDevBranches != nil {
		in, out := &in.PendingDevBranches, &out.PendingDevBranches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchStatus.
func (in *RepoWatchStatus) DeepCopy() *RepoWatchStatus {
	if in == nil {
		return nil
	}
	out := new(RepoWatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedIssue) DeepCopyInto(out *WatchedIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedIssue.
func (in *WatchedIssue) DeepCopy() *WatchedIssue {
	if in == nil {
		return nil
	}
	out := new(WatchedIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedPR) DeepCopyInto(out *WatchedPR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedPR.
func (in *WatchedPR) DeepCopy() *WatchedPR {
	if in == nil {
		return nil
	}
	out := new(WatchedPR)
	in.DeepCopyInto(out)
	return out
}
