package conventions

import "testing"

// TestIsAnnouncement covers what may and may not be dismissed as the watcher
// talking about itself.
//
// The cost of a false positive is high: an announcement is excluded from the
// evidence that feedback has been answered, so anything wrongly read as one
// stops counting as a reply and lets already-handled feedback be picked up
// again.
func TestIsAnnouncement(t *testing.T) {
	tests := []struct {
		name string
		body string
		want bool
	}{
		{
			name: "a tagged announcement",
			body: Announce("🤖 AI Factory started reviewing this pull request in a sandbox."),
			want: true,
		},
		{
			// Pull requests that were open when the marker was introduced hold
			// announcements that will never carry one.
			name: "an announcement posted before the marker existed",
			body: "🤖 AI Factory started addressing review feedback for this pull request.",
			want: true,
		},
		{
			name: "a multi-line announcement posted before the marker existed",
			body: "🤖 AI Factory started investigating CI check failures for this pull request.\n\nNote: We recommend waiting for the 'ready-for-human' label.",
			want: true,
		},
		{
			// The give-up notice reports an outcome, which is a genuine answer
			// to the feedback it is about.
			name: "the watcher giving up on feedback",
			body: "🤖 AI Factory attempted to address this review feedback 3 times without success.",
			want: false,
		},
		{
			name: "an agent's reply to a reviewer",
			body: "Renamed as suggested.\n\n*(This comment was generated by factory)*",
			want: false,
		},
		{
			// A human quoting an announcement back is still a human speaking,
			// and the quote puts the text off the front of the body.
			name: "a human quoting an announcement",
			body: "> 🤖 AI Factory started reviewing this pull request in a sandbox.\n\nIt did not, though.",
			want: false,
		},
		{
			name: "an empty body",
			body: "",
			want: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := IsAnnouncement(tc.body); got != tc.want {
				t.Errorf("IsAnnouncement(%q) = %v, want %v", tc.body, got, tc.want)
			}
		})
	}
}

// TestAnnounceLeavesBodyReadable checks that tagging a comment does not disturb
// what a human sees, and that an empty body stays empty: the watcher takes an
// empty announcement to mean it has nothing to say, and must not be handed a
// marker to post on its own.
func TestAnnounceLeavesBodyReadable(t *testing.T) {
	const body = "🤖 AI Factory started reviewing this pull request in a sandbox."
	got := Announce(body)
	if len(got) <= len(body) || got[:len(body)] != body {
		t.Errorf("Announce(%q) = %q, want it to begin with the original body", body, got)
	}
	if Announce("") != "" {
		t.Errorf("Announce(\"\") = %q, want an empty body left empty", Announce(""))
	}
}
