apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sandbox
  namespace: repo-agent-system
  labels:
    app: dev-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-sandbox
rules:
- apiGroups:
  - "agents.x-k8s.io"
  resources:
  - sandboxes
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - "custom.agents.x-k8s.io"
  resources:
  - sandboxtasks
  - sandboxtasks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "configdir.gke.io"
  resources:
  - configdirs
  - configfiles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-sandbox
subjects:
- kind: ServiceAccount
  name: dev-sandbox
  namespace: repo-agent-system
roleRef:
  kind: ClusterRole
  name: dev-sandbox
  apiGroup: rbac.authorization.k8s.io
