apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: issue-sandbox
spec:
  schema:
    apiVersion: v1alpha1
    group: custom.agents.x-k8s.io
    kind: IssueSandbox
    spec:
      # Spec fields that users can provide.
      replicas: integer | default=1
      llmBackend:
        name: string | default="gemini-cli"
      llm:
        prompt: string | default=""
        configdirRef: string | default=""
        apiKeySecretName: string
      serviceAccountName: string | default="issue-sandbox"
      devcontainerConfigRef: string | default="devcontainer-json"
      image: string | default=""
      githubSecretName: string | default="github-pat"
      resources:
        ephemeralStorage: string | default="6Gi"
        memoryRequest: string | default="2Gi"
        memoryLimit: string | default="6Gi"
      dockerEnabled: boolean | default=false
      source:
        cloneURL: string
        htmlURL: string
        issue: string | default=""
        title: string | default=""
        repo: string | default=""
        handler: string | default=""
      user:
        dotFilesRepo: string | default=""
      destination:
        pushEnabled: boolean | default=false
        branch: string
        origin: string | default=""
        user:
          login: string
          name: string | default="gemini"
          email: string | default="gemini@gemini.ai"
        bot:
          login: string | default=""
          name: string | default=""
          email: string | default=""
      networkPolicy:
        enabled: boolean | default=false
        ingress:
          podLabels: "map[string]string"
          namespaceLabels: "map[string]string"
        egress: object
      gateway:
        httpEnabled: boolean | default=false
        ref: string | default="repo-agent-gateway"
    status:
      # Fields the controller will inject into instances status.
      # agentDraft: "${sandbox.metadata.name}"
      fqdn: ${service.metadata.name}.${service.metadata.namespace}.svc.cluster.local
      sandboxConditions: "${schema.spec.dockerEnabled ? sandboxDocker.status.conditions : sandboxStandard.status.conditions}"
  resources:
    - id: sandboxDocker
      includeWhen:
      - ${schema.spec.dockerEnabled}
      readyWhen: # CEL expressions to determine when a resource is ready
      - ${sandboxDocker.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
      template:
        apiVersion: agents.x-k8s.io/v1alpha1
        kind: Sandbox
        metadata:
          name: devc-${schema.metadata.name} # Use the name provided by user
        spec:
          replicas: ${schema.spec.replicas}
          podTemplate:
            metadata:
              labels:
                sandbox: devc-${schema.metadata.name}
                sandbox-type: issue
            spec:
              runtimeClassName: gvisor
              serviceAccountName: ${schema.spec.serviceAccountName}
              initContainers:
                - name: gemini-configs
                  image: ko://repo-agent/configdir/cmd/configdir-cli
                  args: ["--directory", "/workspaces", "--namespace", "${schema.metadata.namespace}" ,  "--name", "${schema.spec.llm.configdirRef}", "--ignore-not-found-error"]
                  volumeMounts:
                    - name: workspaces-pvc
                      mountPath: /workspaces
                - name: inject-agent
                  image: ko://repo-agent/images/repo-sandbox
                  command: ["/repo-agent/repo-sandbox", "inject", "--path", "/opt/repo-agent"]
                  volumeMounts:
                    - name: agent-bin
                      mountPath: /opt/repo-agent
              containers:
                - name: sandbox
                  image: ${schema.spec.image != "" ? schema.spec.image:"ko://repo-agent/images/repo-sandbox"}
                  command: ${schema.spec.image != "" ? ["/opt/repo-agent/repo-sandbox", "dev-daemon"]:[]}
                  securityContext:
                    privileged: true
                  resources:
                    limits:
                      ephemeral-storage: ${schema.spec.resources.ephemeralStorage}
                      memory: ${schema.spec.resources.memoryLimit}
                    requests:
                      ephemeral-storage: ${schema.spec.resources.ephemeralStorage}
                      memory: ${schema.spec.resources.memoryRequest}
                  env:
                    - name: NAMESPACE
                      value: ${schema.metadata.namespace}
                    - name: DOCKER_ENABLED
                      value: ${string(schema.spec.dockerEnabled)}
                    - name: NAME
                      value: ${schema.metadata.name}
                    - name: REPO
                      value: ${schema.spec.source.repo}
                    - name: HANDLER
                      value: ${schema.spec.source.handler}
                    # URL to the repository where the .devcontainer folder we want to load is located
                    - name: AGENT_NAME
                      value: ${schema.spec.llmBackend.name}
                    - name: AGENT_PROMPT
                      value: ${schema.spec.llm.prompt}
                    - name: ISSUEID
                      value: ${schema.spec.source.issue}
                    - name: ISSUE_BRANCH
                      value: ${schema.spec.destination.branch}
                    - name: USER_DOTFILESREPO
                      value: ${schema.spec.user.dotFilesRepo}
                    - name: DEV_BRANCH
                      value: ${schema.spec.destination.branch}
                    - name: GIT_HTML_URL
                      value: ${schema.spec.source.htmlURL}
                    - name: ISSUE_URL
                      value: ${schema.spec.source.htmlURL}
                    - name: GITHUB_USER_ORIGIN
                      value: ${schema.spec.destination.origin}
                    - name: GITHUB_USER_LOGIN
                      value: ${schema.spec.destination.user.login}
                    - name: GITHUB_USER_NAME
                      value: ${schema.spec.destination.user.name}
                    - name: GITHUB_USER_EMAIL
                      value: ${schema.spec.destination.user.email}
                    - name: GIT_AUTHOR_NAME
                      value: ${schema.spec.destination.user.name}
                    - name: GIT_AUTHOR_EMAIL
                      value: ${schema.spec.destination.user.email}
                    - name: GITHUB_BOT_LOGIN
                      value: ${schema.spec.destination.bot.login}
                    - name: GITHUB_BOT_NAME
                      value: ${schema.spec.destination.bot.name}
                    - name: GITHUB_BOT_EMAIL
                      value: ${schema.spec.destination.bot.email}
                    - name: GITHUB_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.githubSecretName}
                          key: pat
                          optional: true
                    - name: MANUAL_PAT
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.githubSecretName}
                          key: manual_pat
                          optional: true
                    - name: OAUTH_PAT
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.githubSecretName}
                          key: oauth_pat
                          optional: true
                    - name: GIT_PUSH_ENABLED
                      value: ${string(schema.spec.destination.pushEnabled)}
                    - name: GIT_CLONE_URL
                      value: ${schema.spec.source.cloneURL}
                    - name: ENVBUILDER_GIT_URL
                      value: ${schema.spec.source.cloneURL}
                    # https://github.com/coder/terraform-provider-envbuilder/issues/68#issuecomment-2557247792
                    #- name: ENVBUILDER_GET_CACHED_IMAGE
                    #  value: "1"
                    - name: ENVBUILDER_CACHE_REPO
                      value: registry.repo-agent-system.svc.cluster.local:5000/envbuilder-cache
                    - name: ENVBUILDER_DEVCONTAINER_DIR
                      value: /
                    #- name: ENVBUILDER_DOCKERFILE_PATH
                    #  value: ${schema.spec.devcontainerDockerfile}
                    #- name: ENVBUILDER_GIT_CLONE_SINGLE_BRANCH
                    #  value: "true"
                    - name: ENVBUILDER_INIT_SCRIPT
                      value: /opt/repo-agent/repo-sandbox dev-daemon
                    - name: ENVBUILDER_IGNORE_PATHS
                      value: "/var/run,/product_uuid,/product_name,/tokens,/repo-agent/"
                  volumeMounts:
                    - name: workspaces-pvc
                      mountPath: /workspaces
                    - name: tokens-secret
                      mountPath: "/tokens"
                      readOnly: true
                    - name: devcontainer-config
                      mountPath: /devcontainer.json
                      subPath: devcontainer.json
                    - name: agent-bin
                      mountPath: /opt/repo-agent
                  ports:
                    - containerPort: 13337
                    - containerPort: 13339
              volumes:
              - name: agent-bin
                emptyDir: {}
              # configmap volume for devcontainer.json mounting
              - name: devcontainer-config
                configMap:
                  name: ${schema.spec.devcontainerConfigRef}
              # secret volume for LLM API keys
              - name: tokens-secret
                secret:
                  secretName: ${schema.spec.llm.apiKeySecretName}
          volumeClaimTemplates:
            - metadata:
                name: workspaces-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
    - id: sandboxStandard
      includeWhen:
      - ${!schema.spec.dockerEnabled}
      readyWhen: # CEL expressions to determine when a resource is ready
      - ${sandboxStandard.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
      template:
        apiVersion: agents.x-k8s.io/v1alpha1
        kind: Sandbox
        metadata:
          name: devc-${schema.metadata.name} # Use the name provided by user
        spec:
          replicas: ${schema.spec.replicas}
          podTemplate:
            metadata:
              labels:
                sandbox: devc-${schema.metadata.name}
                sandbox-type: issue
            spec:
              serviceAccountName: ${schema.spec.serviceAccountName}
              initContainers:
                - name: gemini-configs
                  image: ko://repo-agent/configdir/cmd/configdir-cli
                  args: ["--directory", "/workspaces", "--namespace", "${schema.metadata.namespace}" ,  "--name", "${schema.spec.llm.configdirRef}", "--ignore-not-found-error"]
                  volumeMounts:
                    - name: workspaces-pvc
                      mountPath: /workspaces
                - name: inject-agent
                  image: ko://repo-agent/images/repo-sandbox
                  command: ["/repo-agent/repo-sandbox", "inject", "--path", "/opt/repo-agent"]
                  volumeMounts:
                    - name: agent-bin
                      mountPath: /opt/repo-agent
              containers:
                - name: sandbox
                  image: ${schema.spec.image != "" ? schema.spec.image:"ko://repo-agent/images/repo-sandbox"}
                  command: ${schema.spec.image != "" ? ["/opt/repo-agent/repo-sandbox", "dev-daemon"]:[]}
                  securityContext:
                    privileged: false
                  resources:
                    limits:
                      ephemeral-storage: ${schema.spec.resources.ephemeralStorage}
                      memory: ${schema.spec.resources.memoryLimit}
                    requests:
                      ephemeral-storage: ${schema.spec.resources.ephemeralStorage}
                      memory: ${schema.spec.resources.memoryRequest}
                  env:
                    - name: NAMESPACE
                      value: ${schema.metadata.namespace}
                    - name: DOCKER_ENABLED
                      value: ${string(schema.spec.dockerEnabled)}
                    - name: NAME
                      value: ${schema.metadata.name}
                    - name: REPO
                      value: ${schema.spec.source.repo}
                    - name: HANDLER
                      value: ${schema.spec.source.handler}
                    # URL to the repository where the .devcontainer folder we want to load is located
                    - name: AGENT_NAME
                      value: ${schema.spec.llmBackend.name}
                    - name: AGENT_PROMPT
                      value: ${schema.spec.llm.prompt}
                    - name: ISSUEID
                      value: ${schema.spec.source.issue}
                    - name: ISSUE_BRANCH
                      value: ${schema.spec.destination.branch}
                    - name: USER_DOTFILESREPO
                      value: ${schema.spec.user.dotFilesRepo}
                    - name: DEV_BRANCH
                      value: ${schema.spec.destination.branch}
                    - name: GIT_HTML_URL
                      value: ${schema.spec.source.htmlURL}
                    - name: ISSUE_URL
                      value: ${schema.spec.source.htmlURL}
                    - name: GITHUB_USER_ORIGIN
                      value: ${schema.spec.destination.origin}
                    - name: GITHUB_USER_LOGIN
                      value: ${schema.spec.destination.user.login}
                    - name: GITHUB_USER_NAME
                      value: ${schema.spec.destination.user.name}
                    - name: GITHUB_USER_EMAIL
                      value: ${schema.spec.destination.user.email}
                    - name: GIT_AUTHOR_NAME
                      value: ${schema.spec.destination.user.name}
                    - name: GIT_AUTHOR_EMAIL
                      value: ${schema.spec.destination.user.email}
                    - name: GITHUB_BOT_LOGIN
                      value: ${schema.spec.destination.bot.login}
                    - name: GITHUB_BOT_NAME
                      value: ${schema.spec.destination.bot.name}
                    - name: GITHUB_BOT_EMAIL
                      value: ${schema.spec.destination.bot.email}
                    - name: GITHUB_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.githubSecretName}
                          key: pat
                          optional: true
                    - name: MANUAL_PAT
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.githubSecretName}
                          key: manual_pat
                          optional: true
                    - name: OAUTH_PAT
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.githubSecretName}
                          key: oauth_pat
                          optional: true
                    - name: GIT_PUSH_ENABLED
                      value: ${string(schema.spec.destination.pushEnabled)}
                    - name: GIT_CLONE_URL
                      value: ${schema.spec.source.cloneURL}
                    - name: ENVBUILDER_GIT_URL
                      value: ${schema.spec.source.cloneURL}
                    # https://github.com/coder/terraform-provider-envbuilder/issues/68#issuecomment-2557247792
                    #- name: ENVBUILDER_GET_CACHED_IMAGE
                    #  value: "1"
                    - name: ENVBUILDER_CACHE_REPO
                      value: registry.repo-agent-system.svc.cluster.local:5000/envbuilder-cache
                    - name: ENVBUILDER_DEVCONTAINER_DIR
                      value: /
                    #- name: ENVBUILDER_DOCKERFILE_PATH
                    #  value: ${schema.spec.devcontainerDockerfile}
                    #- name: ENVBUILDER_GIT_CLONE_SINGLE_BRANCH
                    #  value: "true"
                    - name: ENVBUILDER_INIT_SCRIPT
                      value: /opt/repo-agent/repo-sandbox dev-daemon
                    - name: ENVBUILDER_IGNORE_PATHS
                      value: "/var/run,/product_uuid,/product_name,/tokens,/repo-agent/"
                  volumeMounts:
                    - name: workspaces-pvc
                      mountPath: /workspaces
                    - name: tokens-secret
                      mountPath: "/tokens"
                      readOnly: true
                    - name: devcontainer-config
                      mountPath: /devcontainer.json
                      subPath: devcontainer.json
                    - name: agent-bin
                      mountPath: /opt/repo-agent
                  ports:
                    - containerPort: 13337
                    - containerPort: 13339
              volumes:
              - name: agent-bin
                emptyDir: {}
              # configmap volume for devcontainer.json mounting
              - name: devcontainer-config
                configMap:
                  name: ${schema.spec.devcontainerConfigRef}
              # secret volume for LLM API keys
              - name: tokens-secret
                secret:
                  secretName: ${schema.spec.llm.apiKeySecretName}
          volumeClaimTemplates:
            - metadata:
                name: workspaces-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: devc-${schema.metadata.name}-lb
        spec:
          selector:
            sandbox: devc-${schema.metadata.name}
          ports:
            - name: code-server
              protocol: TCP
              port: 13338
              targetPort: 13337
              appProtocol: kubernetes.io/ws
              #appProtocol: kubernetes.io/h2c
            - name: agent-server
              protocol: TCP
              port: 13339
              targetPort: 13339
    - id: nwpolicy
      includeWhen:
        - ${schema.spec.networkPolicy.enabled}
      template:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-frontend-to-backend
          namespace: default
        spec:
          podSelector:
            matchLabels:
              sandbox: devc-${schema.metadata.name}
          policyTypes:
            - Ingress
            - Egress
          ingress:
          - from:
            - podSelector:
                matchLabels: ${schema.spec.networkPolicy.ingress.podLabels}
            - namespaceSelector:
                matchLabels: ${schema.spec.networkPolicy.ingress.namespaceLabels}
          egress: ${schema.spec.networkPolicy.egress}