apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: sandbox-task
spec:
  schema:
    apiVersion: v1alpha1
    group: custom.agents.x-k8s.io
    kind: SandboxTask
    spec:
      sandboxName: string
      type: string
      params: map[string]string | default={}
      script: string | default=""
    status:
      taskState: string | default="Pending" # Pending, Running, Completed, Failed
      result: string | default=""
  resources: []
