//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubSecretRef) DeepCopyInto(out *GithubSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubSecretRef.
func (in *GithubSecretRef) DeepCopy() *GithubSecretRef {
	if in == nil {
		return nil
	}
	out := new(GithubSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingPR) DeepCopyInto(out *PendingPR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingPR.
func (in *PendingPR) DeepCopy() *PendingPR {
	if in == nil {
		return nil
	}
	out := new(PendingPR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatch) DeepCopyInto(out *RepoWatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatch.
func (in *RepoWatch) DeepCopy() *RepoWatch {
	if in == nil {
		return nil
	}
	out := new(RepoWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoWatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchList) DeepCopyInto(out *RepoWatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepoWatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchList.
func (in *RepoWatchList) DeepCopy() *RepoWatchList {
	if in == nil {
		return nil
	}
	out := new(RepoWatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoWatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchSpec) DeepCopyInto(out *RepoWatchSpec) {
	*out = *in
	out.GithubSecretRef = in.GithubSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchSpec.
func (in *RepoWatchSpec) DeepCopy() *RepoWatchSpec {
	if in == nil {
		return nil
	}
	out := new(RepoWatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchStatus) DeepCopyInto(out *RepoWatchStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WatchedPRs != nil {
		in, out := &in.WatchedPRs, &out.WatchedPRs
		*out = make([]WatchedPR, len(*in))
		copy(*out, *in)
	}
	if in.PendingPRs != nil {
		in, out := &in.PendingPRs, &out.PendingPRs
		*out = make([]PendingPR, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchStatus.
func (in *RepoWatchStatus) DeepCopy() *RepoWatchStatus {
	if in == nil {
		return nil
	}
	out := new(RepoWatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedPR) DeepCopyInto(out *WatchedPR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedPR.
func (in *WatchedPR) DeepCopy() *WatchedPR {
	if in == nil {
		return nil
	}
	out := new(WatchedPR)
	in.DeepCopyInto(out)
	return out
}
