package github

import (
	"context"
	"strings"
	"time"

	"github.com/google/go-github/v39/github"
)

// LimitReachedCommentBody is the standard message posted when the bot reaches its retry limit.
const LimitReachedCommentBody = "The bot has reached its retry limit (2) for investigating failures on this PR since the last human commit. Human intervention is required to address sticky failures.\n\n<!-- OVERSEER_LIMIT_REACHED -->\n\n*(This comment was generated by Overseer)*"

// GetLastHumanCommitTime returns the timestamp of the last commit made by a human (not the bot).
// It iterates backwards from the last page to find the most recent human commit efficiently.
func GetLastHumanCommitTime(ctx context.Context, client *github.Client, owner, repo string, prNumber int, botLogin string, prCreationTime time.Time) (time.Time, error) {
	opts := &github.ListOptions{PerPage: 100}

	// Make an initial request to get pagination information
	// GitHub ListCommits returns chronological order, so newest are on the last page.
	commits, resp, err := client.PullRequests.ListCommits(ctx, owner, repo, prNumber, opts)
	if err != nil {
		return time.Time{}, err
	}

	lastPage := resp.LastPage
	if lastPage == 0 {
		lastPage = 1 // Only 1 page exists
	}

	for page := lastPage; page >= 1; page-- {
		// Only re-fetch if we are on a different page than the initial request
		// Wait, if lastPage == 1, we already have the commits.
		// If lastPage > 1, the initial request got page 1. We need page `lastPage`, so we fetch it.
		// We will only need to fetch page 1 again if we iterate all the way back to it.
		if page != 1 || lastPage > 1 {
			opts.Page = page
			commits, _, err = client.PullRequests.ListCommits(ctx, owner, repo, prNumber, opts)
			if err != nil {
				return time.Time{}, err
			}
		}

		// Iterate backwards through the commits on this page to find the newest human commit
		for i := len(commits) - 1; i >= 0; i-- {
			c := commits[i]
			isBot := false

			if c.GetAuthor() != nil {
				login := c.GetAuthor().GetLogin()
				isBot = c.GetAuthor().GetType() == "Bot" ||
					strings.EqualFold(login, botLogin) ||
					strings.EqualFold(login, botLogin+"[bot]")
			} else if c.GetCommit() != nil && c.GetCommit().GetAuthor() != nil {
				authorName := c.GetCommit().GetAuthor().GetName()
				isBot = strings.EqualFold(authorName, botLogin) ||
					strings.Contains(strings.ToLower(authorName), "[bot]")
			}

			if !isBot {
				if c.GetCommit() != nil && c.GetCommit().GetAuthor() != nil {
					return c.GetCommit().GetAuthor().GetDate(), nil
				}
			}
		}
	}

	// Fallback to PR creation time if no human commits are found
	return prCreationTime, nil
}

// GetInvestigationStatsSince returns the number of investigation reports and whether a limit-reached comment exists since a given time.
func GetInvestigationStatsSince(ctx context.Context, client *github.Client, owner, repo string, prNumber int, since time.Time, botLogin string) (int, bool, error) {
	count := 0
	hasLimitComment := false
	opts := &github.IssueListCommentsOptions{
		Since:       &since,
		ListOptions: github.ListOptions{PerPage: 100},
	}

	for {
		comments, resp, err := client.Issues.ListComments(ctx, owner, repo, prNumber, opts)
		if err != nil {
			return 0, false, err
		}

		for _, c := range comments {
			if c.GetCreatedAt().After(since) && c.GetUser() != nil {
				login := c.GetUser().GetLogin()
				if strings.EqualFold(login, botLogin) || strings.EqualFold(login, botLogin+"[bot]") {
					body := c.GetBody()
					if strings.Contains(body, "--- INVESTIGATION REPORT ---") {
						count++
					}
					if strings.Contains(body, "<!-- OVERSEER_LIMIT_REACHED -->") {
						hasLimitComment = true
					}
				}
			}
		}

		if resp.NextPage == 0 {
			break
		}
		opts.Page = resp.NextPage
	}

	return count, hasLimitComment, nil
}
