package github

import (
	"context"
	"strings"
	"time"

	"github.com/google/go-github/v39/github"
)

// LimitReachedCommentBody is the standard message posted when the bot reaches its retry limit.
const LimitReachedCommentBody = "The bot has reached its retry limit (2) for investigating failures on this PR since the last human commit. Human intervention is required to address sticky failures.\n\nYou can manually trigger another investigation by pushing a new commit, or by using `/overseer investigate-failures --bypass-retry-limit`.\n\n<!-- OVERSEER_LIMIT_REACHED -->\n\n*(This comment was generated by Overseer)*"

// GetLastHumanCommitTime retrieves the latest commit authored by a human on a PR.
func GetLastHumanCommitTime(ctx context.Context, client *github.Client, owner, repo string, prNumber int, botLogin string, prCreationTime time.Time) (time.Time, error) {
	opts := &github.ListOptions{PerPage: 100}

	commits, resp, err := client.PullRequests.ListCommits(ctx, owner, repo, prNumber, opts)
	if err != nil {
		return time.Time{}, err
	}

	lastPage := resp.LastPage
	if lastPage == 0 {
		lastPage = 1 // Only 1 page exists
	}

	firstPageCommits := commits

	for page := lastPage; page >= 1; page-- {
		if page == 1 {
			commits = firstPageCommits
		} else {
			opts.Page = page
			commits, _, err = client.PullRequests.ListCommits(ctx, owner, repo, prNumber, opts)
			if err != nil {
				return time.Time{}, err
			}
		}

		for i := len(commits) - 1; i >= 0; i-- {
			c := commits[i]

			isBot := false
			if c.GetAuthor() != nil {
				login := c.GetAuthor().GetLogin()
				isBot = c.GetAuthor().GetType() == "Bot" ||
					strings.EqualFold(login, botLogin) ||
					strings.EqualFold(login, botLogin+"[bot]") ||
					strings.HasSuffix(strings.ToLower(login), "[bot]")
			} else if c.GetCommit() != nil && c.GetCommit().GetAuthor() != nil {
				authorName := c.GetCommit().GetAuthor().GetName()
				isBot = strings.EqualFold(authorName, botLogin) ||
					strings.Contains(strings.ToLower(authorName), "[bot]")
			}

			if !isBot {
				return c.GetCommit().GetAuthor().GetDate(), nil
			}
		}
	}

	// If no human commits exist, fallback to PR creation time
	return prCreationTime, nil
}

// GetInvestigationStatsSince returns the number of investigation reports and whether the limit comment exists since the given time.
func GetInvestigationStatsSince(ctx context.Context, client *github.Client, owner, repo string, prNumber int, since time.Time, botLogin string) (int, bool, error) {
	count := 0
	hasLimitComment := false
	opts := &github.IssueListCommentsOptions{
		Since:       &since,
		ListOptions: github.ListOptions{PerPage: 100},
	}

	for {
		comments, resp, err := client.Issues.ListComments(ctx, owner, repo, prNumber, opts)
		if err != nil {
			return 0, false, err
		}

		for _, c := range comments {
			if c.GetCreatedAt().After(since) && c.GetUser() != nil {
				login := c.GetUser().GetLogin()
				if strings.EqualFold(login, botLogin) || strings.EqualFold(login, botLogin+"[bot]") || strings.HasSuffix(strings.ToLower(login), "[bot]") {
					body := c.GetBody()
					if strings.Contains(body, "--- INVESTIGATION REPORT ---") {
						count++
					}
					if strings.Contains(body, "<!-- OVERSEER_LIMIT_REACHED -->") {
						hasLimitComment = true
					}
				}
			}
		}

		if resp.NextPage == 0 {
			break
		}
		opts.Page = resp.NextPage
	}

	return count, hasLimitComment, nil
}
