//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoFixSpec) DeepCopyInto(out *AutoFixSpec) {
	*out = *in
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoFixSpec.
func (in *AutoFixSpec) DeepCopy() *AutoFixSpec {
	if in == nil {
		return nil
	}
	out := new(AutoFixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoardCounts) DeepCopyInto(out *BoardCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoardCounts.
func (in *BoardCounts) DeepCopy() *BoardCounts {
	if in == nil {
		return nil
	}
	out := new(BoardCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeFilters) DeepCopyInto(out *IntakeFilters) {
	*out = *in
	if in.ExcludeLabels != nil {
		in, out := &in.ExcludeLabels, &out.ExcludeLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeFilters.
func (in *IntakeFilters) DeepCopy() *IntakeFilters {
	if in == nil {
		return nil
	}
	out := new(IntakeFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeSpec) DeepCopyInto(out *IntakeSpec) {
	*out = *in
	in.AutoFix.DeepCopyInto(&out.AutoFix)
	in.Filters.DeepCopyInto(&out.Filters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeSpec.
func (in *IntakeSpec) DeepCopy() *IntakeSpec {
	if in == nil {
		return nil
	}
	out := new(IntakeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsSpec) DeepCopyInto(out *LimitsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsSpec.
func (in *LimitsSpec) DeepCopy() *LimitsSpec {
	if in == nil {
		return nil
	}
	out := new(LimitsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	if in.DraftPR != nil {
		in, out := &in.DraftPR, &out.DraftPR
		*out = new(bool)
		**out = **in
	}
	if in.AutoIterate != nil {
		in, out := &in.AutoIterate, &out.AutoIterate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrepIdentitySpec) DeepCopyInto(out *PrepIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrepIdentitySpec.
func (in *PrepIdentitySpec) DeepCopy() *PrepIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(PrepIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadySpec) DeepCopyInto(out *ReadySpec) {
	*out = *in
	if in.RequiredChecks != nil {
		in, out := &in.RequiredChecks, &out.RequiredChecks
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadySpec.
func (in *ReadySpec) DeepCopy() *ReadySpec {
	if in == nil {
		return nil
	}
	out := new(ReadySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoBoard) DeepCopyInto(out *RepoBoard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoBoard.
func (in *RepoBoard) DeepCopy() *RepoBoard {
	if in == nil {
		return nil
	}
	out := new(RepoBoard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoBoard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoBoardList) DeepCopyInto(out *RepoBoardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepoBoard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoBoardList.
func (in *RepoBoardList) DeepCopy() *RepoBoardList {
	if in == nil {
		return nil
	}
	out := new(RepoBoardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoBoardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoBoardSpec) DeepCopyInto(out *RepoBoardSpec) {
	*out = *in
	in.Access.DeepCopyInto(&out.Access)
	in.Triggers.DeepCopyInto(&out.Triggers)
	in.Intake.DeepCopyInto(&out.Intake)
	in.Ready.DeepCopyInto(&out.Ready)
	in.Policy.DeepCopyInto(&out.Policy)
	out.Limits = in.Limits
	out.Sandbox = in.Sandbox
	out.PrepIdentity = in.PrepIdentity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoBoardSpec.
func (in *RepoBoardSpec) DeepCopy() *RepoBoardSpec {
	if in == nil {
		return nil
	}
	out := new(RepoBoardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoBoardStatus) DeepCopyInto(out *RepoBoardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Counts = in.Counts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoBoardStatus.
func (in *RepoBoardStatus) DeepCopy() *RepoBoardStatus {
	if in == nil {
		return nil
	}
	out := new(RepoBoardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSpec.
func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggersSpec) DeepCopyInto(out *TriggersSpec) {
	*out = *in
	if in.Discreet != nil {
		in, out := &in.Discreet, &out.Discreet
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggersSpec.
func (in *TriggersSpec) DeepCopy() *TriggersSpec {
	if in == nil {
		return nil
	}
	out := new(TriggersSpec)
	in.DeepCopyInto(out)
	return out
}
