//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueHandlerSpec) DeepCopyInto(out *IssueHandlerSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	out.LLM = in.LLM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueHandlerSpec.
func (in *IssueHandlerSpec) DeepCopy() *IssueHandlerSpec {
	if in == nil {
		return nil
	}
	out := new(IssueHandlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfig) DeepCopyInto(out *LLMConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfig.
func (in *LLMConfig) DeepCopy() *LLMConfig {
	if in == nil {
		return nil
	}
	out := new(LLMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRReviewSpec) DeepCopyInto(out *PRReviewSpec) {
	*out = *in
	out.LLM = in.LLM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRReviewSpec.
func (in *PRReviewSpec) DeepCopy() *PRReviewSpec {
	if in == nil {
		return nil
	}
	out := new(PRReviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingIssue) DeepCopyInto(out *PendingIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingIssue.
func (in *PendingIssue) DeepCopy() *PendingIssue {
	if in == nil {
		return nil
	}
	out := new(PendingIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingPR) DeepCopyInto(out *PendingPR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingPR.
func (in *PendingPR) DeepCopy() *PendingPR {
	if in == nil {
		return nil
	}
	out := new(PendingPR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatch) DeepCopyInto(out *RepoWatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatch.
func (in *RepoWatch) DeepCopy() *RepoWatch {
	if in == nil {
		return nil
	}
	out := new(RepoWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoWatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchList) DeepCopyInto(out *RepoWatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepoWatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchList.
func (in *RepoWatchList) DeepCopy() *RepoWatchList {
	if in == nil {
		return nil
	}
	out := new(RepoWatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoWatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchSpec) DeepCopyInto(out *RepoWatchSpec) {
	*out = *in
	out.Review = in.Review
	if in.IssueHandlers != nil {
		in, out := &in.IssueHandlers, &out.IssueHandlers
		*out = make([]IssueHandlerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchSpec.
func (in *RepoWatchSpec) DeepCopy() *RepoWatchSpec {
	if in == nil {
		return nil
	}
	out := new(RepoWatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoWatchStatus) DeepCopyInto(out *RepoWatchStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WatchedPRs != nil {
		in, out := &in.WatchedPRs, &out.WatchedPRs
		*out = make([]WatchedPR, len(*in))
		copy(*out, *in)
	}
	if in.PendingPRs != nil {
		in, out := &in.PendingPRs, &out.PendingPRs
		*out = make([]PendingPR, len(*in))
		copy(*out, *in)
	}
	if in.WatchedIssues != nil {
		in, out := &in.WatchedIssues, &out.WatchedIssues
		*out = make(map[string][]WatchedIssue, len(*in))
		for key, val := range *in {
			var outVal []WatchedIssue
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]WatchedIssue, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.PendingIssues != nil {
		in, out := &in.PendingIssues, &out.PendingIssues
		*out = make(map[string][]PendingIssue, len(*in))
		for key, val := range *in {
			var outVal []PendingIssue
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]PendingIssue, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoWatchStatus.
func (in *RepoWatchStatus) DeepCopy() *RepoWatchStatus {
	if in == nil {
		return nil
	}
	out := new(RepoWatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedIssue) DeepCopyInto(out *WatchedIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedIssue.
func (in *WatchedIssue) DeepCopy() *WatchedIssue {
	if in == nil {
		return nil
	}
	out := new(WatchedIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedPR) DeepCopyInto(out *WatchedPR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedPR.
func (in *WatchedPR) DeepCopy() *WatchedPR {
	if in == nil {
		return nil
	}
	out := new(WatchedPR)
	in.DeepCopyInto(out)
	return out
}
