apiVersion: overseer.gemini.google.com/v1alpha1
kind: Overseer
metadata:
  name: ai-factory
spec:
  repoURL: https://github.com/ai-on-gke/ai-factory
  robotAccount: factorybot-robot
  chores:
    mode: enabled
  geminiAPIKeySecretName: gemini-vscode-tokens
  image: ghcr.io/gke-labs/gemini-for-kubernetes-development/factory-golang:latest
