apiVersion: overseer.gemini.google.com/v1alpha1
kind: Overseer
metadata:
  name: gwapi-ref
spec:
  repoURL: https://github.com/gke-labs/gateway-api-reference-implementation
  robotAccount: factorybot-robot
  chores:
    mode: enabled
  geminiAPIKeySecretName: gemini-vscode-tokens
  image: ghcr.io/gke-labs/gemini-for-kubernetes-development/factory-golang:latest
