apiVersion: overseer.gemini.google.com/v1alpha1
kind: Overseer
metadata:
  name: kcc
spec:
  repoURL: https://github.com/GoogleCloudPlatform/k8s-config-connector
  robotAccount: codebot-robot
  maxActiveReviews: 3
  maxActiveIssues: 3
  chores:
    mode: enabled
    #include:
    #  - KCC Release Scheduler
  geminiAPIKeySecretName: gemini-vscode-tokens
  ephemeralStorage: 10Gi
  image: ghcr.io/gke-labs/gemini-for-kubernetes-development/generic-golang:latest
  configdirRef: kcc-agents
  repo:
    issueMode: enabled
    prMode: enabled
    reviewMode: disabled

---
apiVersion: configdir.gke.io/v1alpha1
kind: ConfigDir
metadata:
  name: kcc-agents
  namespace: overseer-kcc
spec:
  files:
  - path: .gemini/settings.json
    source:
      inline: |
        {
          "mcpServers": {
          }
        }
#  - path: .agents/tf2d-create-identity-ref-issues.yaml
#    source:
#      inline: |
#        ---
#        name: Issue for Identity and Reference