apiVersion: overseer.gemini.google.com/v1alpha1
kind: Overseer
metadata:
  name: kcc
spec:
  repoURL: https://github.com/GoogleCloudPlatform/k8s-config-connector
  minNumber: 9000
  robotAccount: argus-watcher-bot
  maxActiveReviews: 20
  maxActiveIssues: 25
  sandboxIdleTimeout: 1h
  chores:
    mode: enabled
    #include:
    #  - KCC Release Scheduler
  geminiAPIKeySecretName: gemini-vscode-tokens
  ephemeralStorage: 10Gi
  image: ghcr.io/gke-labs/gemini-for-kubernetes-development/factory-golang:latest
  workspaceDiskSize: 40Gi
  sandboxCPURequest: "2000m"
  sandboxCPULimit: "8000m"
  sandboxMemoryRequest: "4Gi"
  sandboxMemoryLimit: "16Gi"
  secrets:
    - name: projectaccess
      mountPath: "/etc/pakey"
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/etc/pakey/keys.json"
    - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
      value: "/etc/pakey/keys.json"
    - name: GOOGLE_CLOUD_PROJECT
      value: "cnrm-barni-4"
    - name: CLOUDSDK_CORE_PROJECT
      value: "cnrm-barni-4"
    - name: GCP_PROJECT_ID
      value: "cnrm-barni-4"
  repo:
    issueMode: enabled
    prMode: enabled
    reviewMode: disabled
  roles:
    watcher:
      users:
        - argus-watcher-bot
        #- spock-watcher-bot
    coder:
      users:
        - hopper-coder-bot
        - ada-coder-bot
        - neumann-coder-bot
        - lovelace-coder-bot
    reviewer:
      users:
        - reviewbot-robot
    agent:
      users:
        - daedalus-agent-bot
        - feynman-agent-bot
        - walle-agent-bot
