apiVersion: overseer.gemini.google.com/v1alpha1
kind: Overseer
metadata:
  name: gfkd
spec:
  repoURL: https://github.com/gke-labs/gemini-for-kubernetes-development
  robotAccount: factorybot-robot
  chores:
    mode: disabled
  geminiAPIKeySecretName: gemini-vscode-tokens
  ephemeralStorage: 10Gi
  workspaceStorageClassName: premium-rwo
  image: ghcr.io/gke-labs/gemini-for-kubernetes-development/factory-golang:latest
  repo:
    issueMode: enabled
    prMode: enabled
    reviewMode: enabled
