apiVersion: v1
kind: ServiceAccount
metadata:
  name: overseer-sandbox
  namespace: overseer-system
  labels:
    app: overseer-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseer-sandbox
rules:
- apiGroups: ["overseer.gemini.google.com"]
  resources: ["overseers"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "agents.x-k8s.io"
  resources:
  - sandboxes
  verbs:
  - get
  - update
  - patch
  - list
  - watch
  - create
  - delete
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - "custom.agents.x-k8s.io"
  resources:
  - sandboxtasks
  - sandboxtasks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - "configdir.gke.io"
  resources:
  - configdirs
  - configfiles
  verbs:
  - get
  - list
  - watch
  #- update
  #- create
  #- delete
  #- patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: overseer-sandbox
subjects:
- kind: ServiceAccount
  name: overseer-sandbox
  namespace: overseer-system
roleRef:
  kind: ClusterRole
  name: overseer-sandbox
  apiGroup: rbac.authorization.k8s.io