/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package factorycli

import (
	"strings"
	"testing"
	"time"
)

// The name is mirrored from factory rather than imported, so nothing but
// a matching value proves the two agree. This case is the one the
// cluster actually produced (rsch-agent-sandbox-8a3e2fbc, session
// acpd-smoke-2026-09-26).
func TestResearchSandboxNameMatchesFactory(t *testing.T) {
	got := ResearchSandboxName("agent-sandbox", "acpd-smoke-2026-09-26")
	const want = "rsch-agent-sandbox-8a3e2fbc"
	if got != want {
		t.Errorf("ResearchSandboxName = %q, want %q (the name factory created)", got, want)
	}
	if ResearchShortID("acpd-smoke-2026-09-26") != "8a3e2fbc" {
		t.Errorf("ResearchShortID = %q, want 8a3e2fbc", ResearchShortID("acpd-smoke-2026-09-26"))
	}
}

// Exact values, not just well-formed ones. A mirror that produces a
// legal name factory would never have produced is worse than no mirror:
// it points confidently at a sandbox that does not exist.
//
// These were generated by calling factory's own ResearchSandboxName.
// Regenerate them the same way if that function changes — do not
// hand-edit them to match this package, which would defeat the point.
func TestResearchSandboxNameDerivation(t *testing.T) {
	cases := []struct {
		name    string
		repo    string
		session string
		want    string
	}{
		{"plain", "kubernetes", "s1", "rsch-kubernetes-e8bc163c"},
		{"underscores and dots", "my_repo.v2", "s1", "rsch-my-repo-v2-e8bc163c"},
		{"uppercase", "MyRepo", "s1", "rsch-myrepo-e8bc163c"},
		{"leading and trailing junk", "--repo--", "s1", "rsch-repo-e8bc163c"},
		{"inner punctuation", "a.b_c d", "s1", "rsch-a-b-c-d-e8bc163c"},
		// One dash per rune, not per byte.
		{"unicode", "repo-ünïcødé", "s1", "rsch-repo--n-c-d-e8bc163c"},
		{"very long", strings.Repeat("averylongreponame", 12), "s1",
			"rsch-averylongreponameaverylongreponameaverylongrep-e8bc163c"},
		// Nothing survives the slug, so the name is prefix and digest
		// with the joining dash doubled. Odd, but it is what factory
		// creates, which is the only thing that matters here.
		{"empty repo", "", "s1", "rsch--e8bc163c"},
		{"all punctuation", "___", "s1", "rsch--e8bc163c"},
		{"session with slashes", "kubernetes", "org/team/session-1", "rsch-kubernetes-755303ce"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := ResearchSandboxName(tc.repo, tc.session)
			if got != tc.want {
				t.Errorf("ResearchSandboxName(%q, %q) = %q, want %q", tc.repo, tc.session, got, tc.want)
			}
			if len(got) > 60 {
				t.Errorf("name %q is %d chars, over factory's 60 budget", got, len(got))
			}
			for _, r := range got {
				if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '-' {
					t.Errorf("name %q contains %q, not a legal DNS-1123 label character", got, r)
					break
				}
			}
			if strings.HasPrefix(got, "-") || strings.HasSuffix(got, "-") {
				t.Errorf("name %q starts or ends with a dash", got)
			}
		})
	}
}

// Two sessions on one repo must get two sandboxes: the transcript lives
// on the PVC, so a shared sandbox is a shared conversation.
func TestResearchSandboxNameSeparatesSessions(t *testing.T) {
	if a, b := ResearchSandboxName("kubernetes", "s1"), ResearchSandboxName("kubernetes", "s2"); a == b {
		t.Errorf("distinct sessions collided on %q", a)
	}
}

// The command line is the whole contract with factory. The flags have to
// be the ones `factory recipe research` defines (--topic is the recipe's
// input), and --secret must not be among them: mounting the member secret
// would put the engine key on the sandbox's disk.
func TestResearchArgs(t *testing.T) {
	args := researchArgs(ResearchOptions{
		Namespace: "barney-s",
		RepoURL:   "https://github.com/kubernetes-sigs/agent-sandbox",
		SessionID: "s1",
		Topic:     "how are deletes handled?",
	}, 20*time.Minute)

	joined := strings.Join(args, " ")
	for _, want := range []string{
		"recipe research",
		"--url https://github.com/kubernetes-sigs/agent-sandbox",
		"--session s1",
		"--run-name research/s1",
		"--topic how are deletes handled?",
		"--namespace barney-s",
		"--timeout 20m0s",
		"--detached",
	} {
		if !strings.Contains(joined, want) {
			t.Errorf("args %q missing %q", joined, want)
		}
	}
	if strings.Contains(joined, "--secret") {
		t.Error("args must not mount a secret into the research sandbox")
	}
	if strings.Contains(joined, "--engine") {
		t.Error("no engine asked for, yet one was passed; factory's default should apply")
	}

	withOverrides := researchArgs(ResearchOptions{
		Engine:            "antigravity",
		Image:             "ghcr.io/example/img:tag",
		WorkspaceDiskSize: "50Gi",
	}, time.Minute)
	joined = strings.Join(withOverrides, " ")
	for _, want := range []string{"--image ghcr.io/example/img:tag", "--workspace-disk-size 50Gi", "--engine antigravity"} {
		if !strings.Contains(joined, want) {
			t.Errorf("%q missing from %q", want, joined)
		}
	}
}

// The conversation is the session of the task factory recorded the start
// under; a sandbox `factory research start` made has none.
func TestResearchTask(t *testing.T) {
	a := map[string]string{ResearchRunAnnotation: `{"name":"research/s1","task":"recipe-research-1","startedAt":"2026-10-05T10:00:00Z"}`}
	if got := ResearchTask(a); got != "recipe-research-1" {
		t.Errorf("ResearchTask = %q, want recipe-research-1", got)
	}
	if got := ResearchTask(map[string]string{}); got != "" {
		t.Errorf("ResearchTask without a run = %q, want empty", got)
	}
}

// An unset timeout has to become a real one: factory's --timeout takes a
// duration, and "0s" would cancel the context before the pull starts.
func TestResearchTimeoutDefaults(t *testing.T) {
	if got := researchTimeout(ResearchOptions{}); got != 20*time.Minute {
		t.Errorf("default timeout = %v, want 20m", got)
	}
	if got := researchTimeout(ResearchOptions{Timeout: 90 * time.Second}); got != 90*time.Second {
		t.Errorf("caller timeout = %v, want 90s", got)
	}
	if got := researchTimeout(ResearchOptions{Timeout: -1}); got != 20*time.Minute {
		t.Errorf("negative timeout = %v, want the 20m default", got)
	}
}

// save-notes attaches to the sandbox `research start` made, so it is
// addressed the same way. It takes no secret either — the GitHub token
// it pushes with goes in the child's environment, never on the command
// line, where it would be visible in a process listing.
func TestSaveNotesArgs(t *testing.T) {
	args := saveNotesArgs(SaveNotesOptions{
		Namespace:   "barney-s",
		RepoURL:     "https://github.com/kubernetes-sigs/agent-sandbox",
		SessionID:   "s1",
		GithubToken: "ghp_not_a_real_token",
	}, 5*time.Minute)

	joined := strings.Join(args, " ")
	for _, want := range []string{
		"research save-notes",
		"--url https://github.com/kubernetes-sigs/agent-sandbox",
		"--session s1",
		"--namespace barney-s",
		"--timeout 5m0s",
	} {
		if !strings.Contains(joined, want) {
			t.Errorf("args %q missing %q", joined, want)
		}
	}
	if strings.Contains(joined, "ghp_not_a_real_token") {
		t.Error("the token must not reach the command line")
	}
	if strings.Contains(joined, "--secret") {
		t.Error("save-notes mounts nothing into the sandbox")
	}
	// Not passed at all when there is none. The CLI names the file
	// after the session when nothing else does, and two defaults for
	// one thing is how they drift apart.
	if strings.Contains(joined, "--note") {
		t.Errorf("args %q pass an empty note", joined)
	}
}

// The note is a file named after the conversation, and the name
// travels from the capture that asked for it — not re-derived here,
// where a session renamed since would produce a different one.
func TestSaveNotesArgsCarryTheNote(t *testing.T) {
	args := saveNotesArgs(SaveNotesOptions{
		Namespace: "barney-s",
		RepoURL:   "https://github.com/kubernetes-sigs/agent-sandbox",
		SessionID: "s1",
		Note:      "where-the-retry-loop-terminates.md",
	}, 5*time.Minute)
	if joined := strings.Join(args, " "); !strings.Contains(joined, "--note where-the-retry-loop-terminates.md") {
		t.Errorf("args %q do not name the note", joined)
	}
}

func TestSaveNotesTimeoutDefaults(t *testing.T) {
	if got := saveNotesTimeout(SaveNotesOptions{}); got != 5*time.Minute {
		t.Errorf("default timeout = %v, want 5m", got)
	}
	if got := saveNotesTimeout(SaveNotesOptions{Timeout: 90 * time.Second}); got != 90*time.Second {
		t.Errorf("caller timeout = %v, want 90s", got)
	}
	if got := saveNotesTimeout(SaveNotesOptions{Timeout: -1}); got != 5*time.Minute {
		t.Errorf("negative timeout = %v, want the 5m default", got)
	}
}
