/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package factorycli

import (
	"strings"
	"testing"
	"time"
)

// realFactoryOutput is a verbatim `factory research start` run against
// the cluster. The name mirror and the parser are both pinned to it: if
// factory's derivation or its marker line changes, mirroring it here by
// hand is the thing that silently rots, and only a recorded real output
// catches that.
const realFactoryOutput = `Ensuring research sandbox for kubernetes-sigs/agent-sandbox (session acpd-smoke-2026-09-26)...
Connecting to sandbox rsch-agent-sandbox-8a3e2fbc via envd...
Waiting for sandbox pod rsch-agent-sandbox-8a3e2fbc to become ready (and any terminating pods to exit)...
Preparing checkout of agent-sandbox...
RESEARCH_SANDBOX_READY {"sandbox":"rsch-agent-sandbox-8a3e2fbc","namespace":"barney-s","sessionId":"acpd-smoke-2026-09-26","repo":"agent-sandbox","podIP":"10.68.129.221","port":49984,"cwd":"/workspaces/agent-sandbox"}
`

// The name is mirrored from factory rather than imported, so nothing but
// a matching value proves the two agree. This case is the one the
// cluster actually produced.
func TestResearchSandboxNameMatchesFactory(t *testing.T) {
	got := ResearchSandboxName("agent-sandbox", "acpd-smoke-2026-09-26")
	const want = "rsch-agent-sandbox-8a3e2fbc"
	if got != want {
		t.Errorf("ResearchSandboxName = %q, want %q (the name factory created)", got, want)
	}
	if ResearchShortID("acpd-smoke-2026-09-26") != "8a3e2fbc" {
		t.Errorf("ResearchShortID = %q, want 8a3e2fbc", ResearchShortID("acpd-smoke-2026-09-26"))
	}
}

// Exact values, not just well-formed ones. A mirror that produces a
// legal name factory would never have produced is worse than no mirror:
// it points confidently at a sandbox that does not exist.
//
// These were generated by calling factory's own ResearchSandboxName.
// Regenerate them the same way if that function changes — do not
// hand-edit them to match this package, which would defeat the point.
func TestResearchSandboxNameDerivation(t *testing.T) {
	cases := []struct {
		name    string
		repo    string
		session string
		want    string
	}{
		{"plain", "kubernetes", "s1", "rsch-kubernetes-e8bc163c"},
		{"underscores and dots", "my_repo.v2", "s1", "rsch-my-repo-v2-e8bc163c"},
		{"uppercase", "MyRepo", "s1", "rsch-myrepo-e8bc163c"},
		{"leading and trailing junk", "--repo--", "s1", "rsch-repo-e8bc163c"},
		{"inner punctuation", "a.b_c d", "s1", "rsch-a-b-c-d-e8bc163c"},
		// One dash per rune, not per byte.
		{"unicode", "repo-ünïcødé", "s1", "rsch-repo--n-c-d-e8bc163c"},
		{"very long", strings.Repeat("averylongreponame", 12), "s1",
			"rsch-averylongreponameaverylongreponameaverylongrep-e8bc163c"},
		// Nothing survives the slug, so the name is prefix and digest
		// with the joining dash doubled. Odd, but it is what factory
		// creates, which is the only thing that matters here.
		{"empty repo", "", "s1", "rsch--e8bc163c"},
		{"all punctuation", "___", "s1", "rsch--e8bc163c"},
		{"session with slashes", "kubernetes", "org/team/session-1", "rsch-kubernetes-755303ce"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := ResearchSandboxName(tc.repo, tc.session)
			if got != tc.want {
				t.Errorf("ResearchSandboxName(%q, %q) = %q, want %q", tc.repo, tc.session, got, tc.want)
			}
			if len(got) > 60 {
				t.Errorf("name %q is %d chars, over factory's 60 budget", got, len(got))
			}
			for _, r := range got {
				if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '-' {
					t.Errorf("name %q contains %q, not a legal DNS-1123 label character", got, r)
					break
				}
			}
			if strings.HasPrefix(got, "-") || strings.HasSuffix(got, "-") {
				t.Errorf("name %q starts or ends with a dash", got)
			}
		})
	}
}

// Two sessions on one repo must get two sandboxes: the transcript lives
// on the PVC, so a shared sandbox is a shared conversation.
func TestResearchSandboxNameSeparatesSessions(t *testing.T) {
	if a, b := ResearchSandboxName("kubernetes", "s1"), ResearchSandboxName("kubernetes", "s2"); a == b {
		t.Errorf("distinct sessions collided on %q", a)
	}
}

// The parser is what turns a finished invocation into a dialable
// address, so it has to work on exactly what factory prints — progress
// narration and all.
func TestParseResearchReadyOnRealOutput(t *testing.T) {
	got, err := ParseResearchReady(realFactoryOutput)
	if err != nil {
		t.Fatalf("parsing real factory output: %v", err)
	}
	want := ResearchSandbox{
		Sandbox:   "rsch-agent-sandbox-8a3e2fbc",
		Namespace: "barney-s",
		SessionID: "acpd-smoke-2026-09-26",
		Repo:      "agent-sandbox",
		PodIP:     "10.68.129.221",
		Port:      49984,
		CWD:       "/workspaces/agent-sandbox",
	}
	if got != want {
		t.Errorf("parsed\n %+v\nwant\n %+v", got, want)
	}
	if got.Addr() != "10.68.129.221:49984" {
		t.Errorf("Addr() = %q", got.Addr())
	}
	// The sandbox factory named has to be the one this package would
	// have predicted, or a caller cannot find it from the session id.
	if predicted := ResearchSandboxName(got.Repo, got.SessionID); predicted != got.Sandbox {
		t.Errorf("predicted %q but factory created %q", predicted, got.Sandbox)
	}
}

// An output with no marker means the invocation did not get as far as a
// running sandbox. Reporting that as an error beats handing back a zero
// value that reads as a sandbox at ":0".
func TestParseResearchReadyRejectsUnusableOutput(t *testing.T) {
	cases := []struct {
		name   string
		output string
	}{
		{"empty", ""},
		{"progress only", "Ensuring research sandbox for foo/bar...\nError: creating sandbox CR: forbidden\n"},
		{"marker but not json", "RESEARCH_SANDBOX_READY not json at all\n"},
		{"no address", `RESEARCH_SANDBOX_READY {"sandbox":"rsch-x-1","namespace":"n","port":49984}`},
		{"no port", `RESEARCH_SANDBOX_READY {"sandbox":"rsch-x-1","podIP":"10.0.0.1"}`},
		{"no sandbox name", `RESEARCH_SANDBOX_READY {"podIP":"10.0.0.1","port":49984}`},
		// The marker ends with a separator, so a longer word starting
		// with the same stem is not the marker.
		{"longer word with the same stem", `RESEARCH_SANDBOX_READY_V2 {"sandbox":"rsch-x-1","podIP":"10.0.0.1","port":49984}`},
		// Nor is a mention of it partway through a narration line.
		{"marker mentioned in prose", "waiting for RESEARCH_SANDBOX_READY to appear\n"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := ParseResearchReady(tc.output); err == nil {
				t.Errorf("accepted unusable output %q", tc.output)
			}
		})
	}
}

// If an output somehow carries two markers, the live address is the
// last one; returning the first would dial a pod that has been replaced.
func TestParseResearchReadyTakesTheLastMarker(t *testing.T) {
	output := `RESEARCH_SANDBOX_READY {"sandbox":"rsch-x-1","podIP":"10.0.0.1","port":49984}
RESEARCH_SANDBOX_READY {"sandbox":"rsch-x-1","podIP":"10.0.0.2","port":49984}
`
	got, err := ParseResearchReady(output)
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if got.PodIP != "10.0.0.2" {
		t.Errorf("podIP = %q, want the later 10.0.0.2", got.PodIP)
	}
}

// The command line is the whole contract with factory. The flags have to
// be the ones `factory research start` defines, and --secret must not be
// among them: mounting the member secret would put the engine key on the
// sandbox's disk, which is exactly what the header exists to avoid.
func TestResearchArgs(t *testing.T) {
	args := researchArgs(ResearchOptions{
		Namespace: "barney-s",
		RepoURL:   "https://github.com/kubernetes-sigs/agent-sandbox",
		SessionID: "s1",
	}, 20*time.Minute)

	joined := strings.Join(args, " ")
	for _, want := range []string{
		"research start",
		"--url https://github.com/kubernetes-sigs/agent-sandbox",
		"--session s1",
		"--namespace barney-s",
		"--timeout 20m0s",
	} {
		if !strings.Contains(joined, want) {
			t.Errorf("args %q missing %q", joined, want)
		}
	}
	if strings.Contains(joined, "--secret") {
		t.Error("args must not mount a secret into the research sandbox")
	}
	if strings.Contains(joined, "--engine") {
		t.Error("the engine is chosen at session create, not sandbox create")
	}

	withOverrides := researchArgs(ResearchOptions{
		Image:             "ghcr.io/example/img:tag",
		WorkspaceDiskSize: "50Gi",
	}, time.Minute)
	joined = strings.Join(withOverrides, " ")
	if !strings.Contains(joined, "--image ghcr.io/example/img:tag") {
		t.Errorf("image override missing from %q", joined)
	}
	if !strings.Contains(joined, "--workspace-disk-size 50Gi") {
		t.Errorf("disk size override missing from %q", joined)
	}
}

// An unset timeout has to become a real one: factory's --timeout takes a
// duration, and "0s" would cancel the context before the pull starts.
func TestResearchTimeoutDefaults(t *testing.T) {
	if got := researchTimeout(ResearchOptions{}); got != 20*time.Minute {
		t.Errorf("default timeout = %v, want 20m", got)
	}
	if got := researchTimeout(ResearchOptions{Timeout: 90 * time.Second}); got != 90*time.Second {
		t.Errorf("caller timeout = %v, want 90s", got)
	}
	if got := researchTimeout(ResearchOptions{Timeout: -1}); got != 20*time.Minute {
		t.Errorf("negative timeout = %v, want the 20m default", got)
	}
}
