/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package factorycli

import (
	"strings"
	"testing"
)

// The name is mirrored from factory rather than imported, so nothing but
// a matching value proves the two agree. This case is the one the
// cluster actually produced (rsch-agent-sandbox-8a3e2fbc, session
// acpd-smoke-2026-09-26).
func TestResearchSandboxNameMatchesFactory(t *testing.T) {
	got := ResearchSandboxName("agent-sandbox", "acpd-smoke-2026-09-26")
	const want = "rsch-agent-sandbox-8a3e2fbc"
	if got != want {
		t.Errorf("ResearchSandboxName = %q, want %q (the name factory created)", got, want)
	}
	if ResearchShortID("acpd-smoke-2026-09-26") != "8a3e2fbc" {
		t.Errorf("ResearchShortID = %q, want 8a3e2fbc", ResearchShortID("acpd-smoke-2026-09-26"))
	}
}

// Exact values, not just well-formed ones. A mirror that produces a
// legal name factory would never have produced is worse than no mirror:
// it points confidently at a sandbox that does not exist.
//
// These were generated by calling factory's own ResearchSandboxName.
// Regenerate them the same way if that function changes — do not
// hand-edit them to match this package, which would defeat the point.
func TestResearchSandboxNameDerivation(t *testing.T) {
	cases := []struct {
		name    string
		repo    string
		session string
		want    string
	}{
		{"plain", "kubernetes", "s1", "rsch-kubernetes-e8bc163c"},
		{"underscores and dots", "my_repo.v2", "s1", "rsch-my-repo-v2-e8bc163c"},
		{"uppercase", "MyRepo", "s1", "rsch-myrepo-e8bc163c"},
		{"leading and trailing junk", "--repo--", "s1", "rsch-repo-e8bc163c"},
		{"inner punctuation", "a.b_c d", "s1", "rsch-a-b-c-d-e8bc163c"},
		// One dash per rune, not per byte.
		{"unicode", "repo-ünïcødé", "s1", "rsch-repo--n-c-d-e8bc163c"},
		{"very long", strings.Repeat("averylongreponame", 12), "s1",
			"rsch-averylongreponameaverylongreponameaverylongrep-e8bc163c"},
		// Nothing survives the slug, so the name is prefix and digest
		// with the joining dash doubled. Odd, but it is what factory
		// creates, which is the only thing that matters here.
		{"empty repo", "", "s1", "rsch--e8bc163c"},
		{"all punctuation", "___", "s1", "rsch--e8bc163c"},
		{"session with slashes", "kubernetes", "org/team/session-1", "rsch-kubernetes-755303ce"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := ResearchSandboxName(tc.repo, tc.session)
			if got != tc.want {
				t.Errorf("ResearchSandboxName(%q, %q) = %q, want %q", tc.repo, tc.session, got, tc.want)
			}
			if len(got) > 60 {
				t.Errorf("name %q is %d chars, over factory's 60 budget", got, len(got))
			}
			for _, r := range got {
				if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '-' {
					t.Errorf("name %q contains %q, not a legal DNS-1123 label character", got, r)
					break
				}
			}
			if strings.HasPrefix(got, "-") || strings.HasSuffix(got, "-") {
				t.Errorf("name %q starts or ends with a dash", got)
			}
		})
	}
}

// Two sessions on one repo must get two sandboxes: the transcript lives
// on the PVC, so a shared sandbox is a shared conversation.
func TestResearchSandboxNameSeparatesSessions(t *testing.T) {
	if a, b := ResearchSandboxName("kubernetes", "s1"), ResearchSandboxName("kubernetes", "s2"); a == b {
		t.Errorf("distinct sessions collided on %q", a)
	}
}

// The conversation is the session of the task factory recorded the start
// under; a sandbox the recipe did not start has none.
func TestResearchTask(t *testing.T) {
	a := map[string]string{ResearchRunAnnotation: `{"name":"research/s1","task":"recipe-research-1","startedAt":"2026-10-05T10:00:00Z"}`}
	if got := ResearchTask(a); got != "recipe-research-1" {
		t.Errorf("ResearchTask = %q, want recipe-research-1", got)
	}
	if got := ResearchTask(map[string]string{}); got != "" {
		t.Errorf("ResearchTask without a run = %q, want empty", got)
	}
}
