run:
  timeout: 5m

linters:
  enable:
  - gofmt
  - goimports
  - govet
  - revive
  - staticcheck
  - unconvert
  - misspell
  - errcheck
  - ineffassign

issues:
  exclude-rules:
    - linters:
        - revive
      text: "unused-parameter"
