#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import subprocess
import time
import argparse

def run_command(command):
    """Runs a shell command and prints its output."""
    print(f"Running command: {' '.join(command)}")
    subprocess.run(command, check=True)

def main():
    """Installs or uninstalls the latest version of Kro."""
    parser = argparse.ArgumentParser(description="Installs or uninstalls Kro.")
    parser.add_argument("--uninstall", action="store_true", help="Uninstall Kro.")
    args = parser.parse_args()

    try:
        if args.uninstall:
            print("Uninstalling Kro...")
            run_command(["helm", "uninstall", "kro", "--namespace", "kro"])
            run_command(["kubectl", "delete", "namespace", "kro"])
            print("Kro uninstalled successfully.")
            return

        #kro_version = get_latest_kro_version()
        kro_version = "0.5.1"
        print(f"Installing kro version: {kro_version}")

        # Check if Kro is already installed
        helm_list_command = ["helm", "-n", "kro", "list"]
        result = subprocess.run(helm_list_command, capture_output=True, text=True)
        if "kro" in result.stdout:
            print("Kro is already installed. Skipping installation.")
            return

        helm_install_command = [
            "helm", "install", "kro", "oci://registry.k8s.io/kro/charts/kro",
            "--namespace", "kro",
            "--create-namespace",
            f"--version={kro_version}"
        ]
        run_command(helm_install_command)

        print("Waiting for 5 seconds...")
        time.sleep(5)

        helm_list_command = ["helm", "-n", "kro", "list"]
        run_command(helm_list_command)

        kubectl_get_pods_command = ["kubectl", "get", "pods", "-n", "kro"]
        run_command(kubectl_get_pods_command)

        print("Kro installed successfully.")

    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()