#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import requests
import subprocess
import time

def get_latest_eg_version():
    """Fetches the latest Envoy GW version from the GitHub API."""
    return "v1.5.2"

def run_command(command):
    """Runs a shell command and prints its output."""
    print(f"Running command: {" ".join(command)}")
    subprocess.run(command, check=True)

def main():
    """Installs the latest version of Envoy GW."""
    try:
        eg_version = get_latest_eg_version()
        print(f"Installing Envoy GW version: {eg_version}")

        helm_install_command = [
            "helm", "install", "eg", "oci://docker.io/envoyproxy/gateway-helm", 
            f"--version={eg_version}",
            "-n", "envoy-gateway-system",
            "--create-namespace"
        ]
        run_command(helm_install_command)

        print("Waiting for 5 seconds...")
        time.sleep(5)

        kubectl_wait_command = [
            "kubectl", "wait", "--timeout=5m", "-n", "envoy-gateway-system",
            "deployment/envoy-gateway", "--for=condition=Available"
        ]
        run_command(kubectl_wait_command)

        print("Envoy GW installed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()
