#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import subprocess
import argparse
import sys
import os

from shared import utils

CHAINSAW_VERSION = "v0.2.12"

def install_chainsaw(repo_root):
    """Installs chainsaw if not present or if the version is incorrect."""
    local_bin = os.path.join(repo_root, "bin")
    chainsaw_path = os.path.join(local_bin, "chainsaw")

    if os.path.exists(chainsaw_path):
        try:
            version_output = subprocess.check_output([chainsaw_path, "version"], text=True)
            if CHAINSAW_VERSION in version_output:
                print(f"chainsaw version {CHAINSAW_VERSION} already installed.")
                return
            else:
                print(f"Found incorrect version of chainsaw. Found {version_output} but expected {CHAINSAW_VERSION}. Removing and reinstalling.")
                os.remove(chainsaw_path)
        except (subprocess.CalledProcessError, FileNotFoundError):
            print("Could not determine chainsaw version. Reinstalling.")
            os.remove(chainsaw_path)

    print(f"Installing chainsaw {CHAINSAW_VERSION}...")
    env = os.environ.copy()
    env["GOBIN"] = local_bin
    env["GO111MODULE"] = "on"
    subprocess.run(
        ["go", "install", f"github.com/kyverno/chainsaw@{CHAINSAW_VERSION}"],
        env=env,
        check=True,
        cwd=repo_root,
    )

def main(args):
    """ invokes unit tests and outputs a junit results file """
    repo_root = utils.get_repo_root()
    working_dir = args.working_dir or repo_root
    print(f"using working dir: {working_dir}")
    local_bin = os.path.join(repo_root, "bin")
    chainsaw_path = os.path.join(local_bin, "chainsaw")

    install_chainsaw(repo_root)

    e2e_cmd = [
        chainsaw_path,
        "test",
        "test/e2e"
    ]

    result = subprocess.run(e2e_cmd, cwd=working_dir, check=True)
    return result.returncode


if __name__ == "__main__":
    # parse arguments and call
    parser = argparse.ArgumentParser(description="Run e2e tests using chainsaw")
    parser.add_argument("--working-dir",
                        dest="working_dir",
                        help="use working dir instead of repo root",
                        type=str,
                        default=None)
    args = parser.parse_args()

    sys.exit(main(args))
