name: Build and Publish github-portal

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Clone service-portals repo
        run: |
          git clone https://github.com/gke-labs/service-portals.git service-portals

      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: ./service-portals
          file: ./service-portals/images/service-portal/Dockerfile
          push: true
          tags: ghcr.io/gke-labs/gemini-for-kubernetes-development/github-portal:latest
