name: deploy to autopush

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
        type: string
    secrets:
      GKE_SA_KEY:
        required: true
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (defaults to github.sha)'
        required: false
        type: string

permissions:
  contents: read

jobs:
  deploy-autopush:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Google Auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3
        with:
          cluster_name: ${{ vars.GKE_AUTOPUSH_CLUSTER }}
          location: ${{ vars.GKE_ZONE }}

      - name: Deploy to Autopush
        run: |
          chmod +x ./repo-agent/scripts/upgrade.sh
          ./repo-agent/scripts/upgrade.sh
        env:
          IMAGE_TAG: ${{ inputs.image_tag || github.sha }}
          SKIP_PREQS: 'true'
          CLUSTER_NAME: ${{ vars.GKE_AUTOPUSH_CLUSTER }}
          GW_CLASS: 'gke-l7-regional-external-managed'

      - name: Deploy Overseer to Autopush
        run: |
          chmod +x ./overseer/scripts/upgrade.sh
          ./overseer/scripts/upgrade.sh
        env:
          IMAGE_TAG: ${{ inputs.image_tag || github.sha }}
          SKIP_PREQS: 'true'
          CLUSTER_NAME: ${{ vars.GKE_AUTOPUSH_CLUSTER }}
  deploy-autopush-std:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Google Auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3
        with:
          cluster_name: ${{ vars.GKE_AUTOPUSH_STD_CLUSTER }}
          location: ${{ vars.GKE_ZONE }}

      - name: Deploy to Autopush Standard
        run: |
          chmod +x ./repo-agent/scripts/upgrade.sh
          ./repo-agent/scripts/upgrade.sh
        env:
          IMAGE_TAG: ${{ inputs.image_tag || github.sha }}
          SKIP_PREQS: 'true'
          CLUSTER_NAME: ${{ vars.GKE_AUTOPUSH_STD_CLUSTER }}
          GW_CLASS: 'gke-l7-regional-external-managed'

      - name: Deploy Overseer to Autopush Standard
        run: |
          chmod +x ./overseer/scripts/upgrade.sh
          ./overseer/scripts/upgrade.sh
        env:
          IMAGE_TAG: ${{ inputs.image_tag || github.sha }}
          SKIP_PREQS: 'true'
          CLUSTER_NAME: ${{ vars.GKE_AUTOPUSH_STD_CLUSTER }}
