name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  release-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name:
          - configdir-cli
          - configdir-controller
          - github-mcp-server
          - repowatch-controller
          - review-api
          - repo-sandbox
          - review-ui
          - syncer
          - generic-golang
          - dind-golang
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          # fetch all history so we can get the latest tag
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release images
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: repo-agent/
          file: repo-agent/images/${{ matrix.image_name }}/Dockerfile
          push: true
          tags: |
            ghcr.io/gke-labs/gemini-for-kubernetes-development/${{ matrix.image_name }}:${{ github.ref_name }}

  release-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          # fetch all history so we can get the latest tag
          fetch-depth: 0

      - name: Generate Release Assets
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          chmod +x ./dev/tools/deploy-to-kube
          mkdir release-assets/
          ./dev/tools/deploy-to-kube --image-prefix=ghcr.io/gke-labs/gemini-for-kubernetes-development/ --image-tag="$IMAGE_TAG" --working-dir repo-agent/ --output-file=release-assets/manifest.yaml
          sed "s/{REPO_AGENT_VERSION:=.*}/{REPO_AGENT_VERSION:=$IMAGE_TAG}/g" repo-agent/installer.sh > release-assets/installer.sh
          chmod +x release-assets/installer.sh

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release create "$TAG_NAME" \
            release-assets/manifest.yaml \
            release-assets/installer.sh \
            --title "Release $TAG_NAME"
