package tasks

import (
	"strings"
	"testing"
)

// Every attribution the agent is told to post goes with --disclose, and
// none of it is left behind without: a repo that asked for no agent
// markers gets none, in the PR or in the comments after it.
func TestDiscloseGatesAttribution(t *testing.T) {
	render := map[string]func(disclose bool) ([]byte, error){
		"fix": func(d bool) ([]byte, error) {
			return RenderFixIssuePrompt(FixIssueParams{PRLabel: "factory", Disclose: d})
		},
		"investigate": func(d bool) ([]byte, error) {
			return RenderInvestigatePrompt(InvestigateParams{TriggerLabel: "factory", Disclose: d})
		},
		"address-comments": func(d bool) ([]byte, error) {
			return RenderAddressFeedbackPrompt(AddressFeedbackParams{TriggerLabel: "factory", Disclose: d})
		},
	}
	for name, fn := range render {
		on, err := fn(true)
		if err != nil {
			t.Fatalf("%s: rendering with disclose: %v", name, err)
		}
		if !strings.Contains(string(on), "generated by") {
			t.Errorf("%s: with disclose, the prompt asks for no attribution", name)
		}
		off, err := fn(false)
		if err != nil {
			t.Fatalf("%s: rendering without disclose: %v", name, err)
		}
		if strings.Contains(string(off), "generated by") {
			t.Errorf("%s: without disclose, the prompt still asks for attribution", name)
		}
	}
}
