package tasks

import (
	"strings"
	"testing"
)

// Every attribution the agent is told to post goes with --disclose, and
// none of it is left behind without: a repo that asked for no agent
// markers gets none, in the PR or in the comments after it.
func TestDiscloseGatesAttribution(t *testing.T) {
	render := map[string]func(disclose bool) ([]byte, error){
		"fix": func(d bool) ([]byte, error) {
			return RenderFixIssuePrompt(FixIssueParams{PRLabel: "factory", TriggerLabel: "factory", Disclose: d})
		},
		"investigate": func(d bool) ([]byte, error) {
			return RenderInvestigatePrompt(InvestigateParams{TriggerLabel: "factory", Disclose: d})
		},
		"address-comments": func(d bool) ([]byte, error) {
			return RenderAddressFeedbackPrompt(AddressFeedbackParams{TriggerLabel: "factory", Disclose: d})
		},
	}
	for name, fn := range render {
		on, err := fn(true)
		if err != nil {
			t.Fatalf("%s: rendering with disclose: %v", name, err)
		}
		if !strings.Contains(string(on), "generated by") {
			t.Errorf("%s: with disclose, the prompt asks for no attribution", name)
		}
		off, err := fn(false)
		if err != nil {
			t.Fatalf("%s: rendering without disclose: %v", name, err)
		}
		if strings.Contains(string(off), "generated by") {
			t.Errorf("%s: without disclose, the prompt still asks for attribution", name)
		}
	}
}

// The fix prompt names the agent by its trigger label. PRLabel also carries
// the parent issue's labels, and quoting it produced attributions like
// "generated by the overseer,priority/medium,area/release agent".
func TestFixIssueAttributionNamesTriggerLabel(t *testing.T) {
	out, err := RenderFixIssuePrompt(FixIssueParams{
		PRLabel:      "overseer,priority/medium,area/release",
		TriggerLabel: "overseer",
		Disclose:     true,
	})
	if err != nil {
		t.Fatalf("rendering: %v", err)
	}
	if !strings.Contains(string(out), "generated by the **overseer** agent") {
		t.Errorf("attribution does not name the trigger label:\n%s", out)
	}
	if strings.Contains(string(out), "generated by the **overseer,priority/medium,area/release** agent") {
		t.Errorf("attribution quotes the PR label list")
	}
}

// TestPromptsDoNotHardcodeBotUsers verifies that rendered prompts do not contain legacy hardcoded bot usernames.
func TestPromptsDoNotHardcodeBotUsers(t *testing.T) {
	prompts := map[string]func() ([]byte, error){
		"fix": func() ([]byte, error) {
			return RenderFixIssuePrompt(FixIssueParams{})
		},
		"investigate": func() ([]byte, error) {
			return RenderInvestigatePrompt(InvestigateParams{})
		},
		"address-comments": func() ([]byte, error) {
			return RenderAddressFeedbackPrompt(AddressFeedbackParams{})
		},
	}
	for name, fn := range prompts {
		out, err := fn()
		if err != nil {
			t.Fatalf("%s: rendering prompt: %v", name, err)
		}
		for _, bot := range []string{"codebot-robot", "factorybot-robot"} {
			if strings.Contains(string(out), bot) {
				t.Errorf("%s prompt still contains hardcoded bot name %q:\n%s", name, bot, out)
			}
		}
	}
}

